INFO     lingkuan_828.conftest:conftest.py:62 [2025-08-29 09:09:19] 用例 test_vps/test_delete.py::TestDeleteUser::test_delete_userlist 开始登录，环境: uat
INFO     lingkuan_828.conftest:conftest.py:100 UAT登录尝试 1/5，MFA验证码: 533867
INFO     lingkuan_828.conftest:conftest.py:124 UAT登录成功（第1次尝试）
INFO     lingkuan_828.commons.variable_manager:variable_manager.py:111 [2025-08-29 09:08] 运行时变量已保存到: D:\pycharm_test\lingkuan_828\VAR\runtime_vars_vps.json
INFO     lingkuan_828.commons.api_base:api_base.py:239 [2025-08-29 09:09:21] DELETE请求: /mascontrol/user | 数据: [6757]
INFO     root:test_delete.py:501 第1个账号（ID: 6757）删除接口调用成功
INFO     lingkuan_828.commons.api_base:api_base.py:239 [2025-08-29 09:09:22] DELETE请求: /mascontrol/user | 数据: [6754]
INFO     root:test_delete.py:501 第2个账号（ID: 6754）删除接口调用成功
INFO     lingkuan_828.commons.api_base:api_base.py:239 [2025-08-29 09:09:24] DELETE请求: /mascontrol/user | 数据: [6759]
INFO     root:test_delete.py:501 第3个账号（ID: 6759）删除接口调用成功
INFO     lingkuan_828.commons.api_base:api_base.py:239 [2025-08-29 09:09:26] DELETE请求: /mascontrol/user | 数据: [6753]
INFO     root:test_delete.py:501 第4个账号（ID: 6753）删除接口调用成功
INFO     lingkuan_828.commons.api_base:api_base.py:239 [2025-08-29 09:09:27] DELETE请求: /mascontrol/user | 数据: [6756]
INFO     root:test_delete.py:501 第5个账号（ID: 6756）删除接口调用成功
INFO     lingkuan_828.commons.api_base:api_base.py:239 [2025-08-29 09:09:29] DELETE请求: /mascontrol/user | 数据: [6758]
INFO     root:test_delete.py:501 第6个账号（ID: 6758）删除接口调用成功
INFO     lingkuan_828.commons.api_base:api_base.py:239 [2025-08-29 09:09:30] DELETE请求: /mascontrol/user | 数据: [6755]
INFO     root:test_delete.py:501 第7个账号（ID: 6755）删除接口调用成功
INFO     lingkuan_828.conftest:conftest.py:157 [2025-08-29 09:09:31] 用例 test_vps/test_delete.py::TestDeleteUser::test_delete_userlist 执行完毕