INFO     template.commons.variable_manager:variable_manager.py:40 [2025-09-29 11:18:46] 成功加载静态变量: VAR\uat_data.json
INFO     template.commons.variable_manager:variable_manager.py:64 [2025-09-29 11:18:46] 成功加载运行时变量: VAR\runtime_vars_cloud.json
INFO     template.conftest:conftest.py:74 [2025-09-29 11:18:46] 用例  开始登录，环境: uat
DEBUG    urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): dev.lgcopytrade.top:443
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://dev.lgcopytrade.top:443 "GET /api/sys/randomImage/1759115926886?_t=1759115926 HTTP/11" 200 None
INFO     template.conftest:conftest.py:143 第1次尝试 - 验证码识别结果: Stum
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://dev.lgcopytrade.top:443 "POST /api/sys/login HTTP/11" 200 None
INFO     template.conftest:conftest.py:186 uat环境登录成功（第1次尝试）
INFO     template.commons.variable_manager:variable_manager.py:111 [2025-09-29 11:18:46] 运行时变量已保存到: D:\pycharm_test\template\VAR\runtime_vars_cloud.json
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://dev.lgcopytrade.top:443 "GET /api/blockchain/followVps/getRecordList?_t=1759115926&column=name&order=asc HTTP/11" 200 None
INFO     template.commons.api_base:api_base.py:258 [2025-09-29 11:18:49] GET请求: /blockchain/followVps/getRecordList | 参数: {'_t': 1759115926, 'column': 'name', 'order': 'asc'}
INFO     template.commons.variable_manager:variable_manager.py:111 [2025-09-29 11:18:46] 运行时变量已保存到: D:\pycharm_test\template\VAR\runtime_vars_cloud.json
INFO     template.conftest:conftest.py:225 [2025-09-29 11:18:52] 用例  执行完毕
INFO     template.commons.variable_manager:variable_manager.py:111 [2025-09-29 11:18:46] 运行时变量已保存到: D:\pycharm_test\template\VAR\runtime_vars_cloud.json